spring:
  application:
    name: milfoil-pattern-middle
  datasource:
    url: jdbc:h2:mem:milfoil
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: ${GITHUB_CLIENT_ID:}
            client-secret: ${GITHUB_CLIENT_SECRET:}
            scope: read:user,user:email

  thymeleaf:
    cache: false

server:
  error:
    whitelabel:
      enabled: false